apiVersion: apps/v1
kind: Deployment
metadata:
  name: andy-deployment
  labels:
    app: andy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: andy
  template:
    metadata:
      labels:
        app: andy
    spec:
      containers:
      - name: andy
        image: tankbohr/andy:latest
        env:
        - name: "LOG_LEVEL"
          value: "info"
        - name: "COOKIE"
          value: "0ec50c3a-eb8b-4d93-a9c5-5cf267724f6f"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 6379
